spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:LogifinLocal}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    clean-disabled: false

server:
  port: 8080

logging:
  level:
    com.logifin: DEBUG
    org.hibernate.SQL: DEBUG
